version: '3'

services:
  backend:
    build: ./
    container_name: fusion_container
    working_dir: /fusionstyle
    ports:
      - 8010:8010
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/fusionstyle/src
      - ./commands:/fusionstyle/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    env_file:
      - .env


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  pg_data: { }
  pgadmin_data: { }
  mongodb_data: { }