version: '3'

services:
  backend:
    build: ./
    container_name: fusion_container
    working_dir: /fusionstyle
    ports:
      - 8010:8010
    command:
      - ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/fusionstyle/src
      - ./commands:/fusionstyle/commands
      - static_content:/fusionstyle/src/static_content
      - media_content:/fusionstyle/src/media_content
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    container_name: nginx_container
    volumes:
      - static_content:/fusionstyle/src/static
      - media_content:/fusionstyle/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend



volumes:
  static_content: { }
  media_content: { }
#    depends_on:
#      - postgres

#  postgres:
#    image: postgres:12
#    ports:
#      - 5432:5432
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    env_file:
#      - .env

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    restart: on-failure
#    env_file:
#      - .env
#    ports:
#      - 5000:80
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    depends_on:
#      - postgres


#  redis:
#    image: redis
#    env_file:
#      - .env
#    restart: on-failure
#    depends_on:
#      - backend
#
#
#  celery-flower:
#    build: ./
#    command:
#      - ./commands/start_celery_flower.sh
#    restart: always
#    volumes:
#      - ./src:/fusionstyle
#      - ./commands:/fusionstyle/commands
#    ports:
#      - 5556:5555
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - backend
#
#  redisadmin:
#    image: rediscommander/redis-commander:latest
#    container_name: redisadmin
#    hostname: redisadmin
#    restart: on-failure
#    ports:
#      - 8092:8081
#    env_file: .env
#
#  celerybeat:
#    build: ./
#    container_name: celerybeat-container
#    command:
#      - ./commands/start_celerybeat.sh
#    restart: on-failure
#    volumes:
#      - ./src:/quiz
#      - ./commands:/fusionstyle/commands
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - backend


#  pg_data: { }
#  pgadmin_data: { }
