version: '3'

services:
  backend:
    build: ./
    container_name: fusion_container
    working_dir: /fusionstyle
    ports:
      - 8010:8010
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/fusionstyle/src
      - ./commands:/fusionstyle/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: {}