# Generated by Django 4.2.4 on 2023-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_customer_options_alter_customer_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True, help_text="Maidan Nezalezhnosti 1", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_currency",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "UAH"), (1, "USD"), (2, "EURO")], default=0
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="zipcode",
            field=models.CharField(
                blank=True, help_text="02000", max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True, help_text="\tKyiv", max_length=60, null=True
            ),
        ),
    ]
