# Generated by Django 4.2.4 on 2023-08-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_customer_address_customer_preferred_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
