# Generated by Django 4.2.4 on 2023-08-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_order_updated_at_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="shop/brand/"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(related_name="cart", to="shop.product"),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="order", to="shop.product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="shop.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="shop.category",
            ),
        ),
    ]
